#pragma once

namespace qyhs::initializer
{
	enum INITIALIZED_SYSTEM
	{
		INITIALIZED_SYSTEM_IMAGE,
		INITIALIZED_SYSTEM_FONT,
		INITIALIZED_SYSTEM_TRIANGLE,
		INITIALIZED_SYSTEM_INPUT,
		INITIALIZED_SYSTEM_RENDERER,
		INITIALIZED_SYSTEM_COUNT
	};
	bool initializeFinished();
	void initializeComponentAsync();
}